/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "gestionUsuarios.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
almacenarusuario_1(registroUsuario *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, almacenarUsuario,
		(xdrproc_t) xdr_registroUsuario, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

registroUsuario *
consultarusuario_1(int *argp, CLIENT *clnt)
{
	static registroUsuario clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarUsuario,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_registroUsuario, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

registroUsuario *
autenticar_1(registroUsuario *argp, CLIENT *clnt)
{
	static registroUsuario clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, autenticar,
		(xdrproc_t) xdr_registroUsuario, (caddr_t) argp,
		(xdrproc_t) xdr_registroUsuario, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
