/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"

bool_t *
registrarusuario_1_svc(datos_usuario *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_usuario *
iniciarsesion_1_svc(datos_usuario *argp, struct svc_req *rqstp)
{
	static datos_usuario  result;

	/*
	 * insert server code here
	 */

	return &result;
}
