/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"


void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	registroUsuario  almacenarusuario_1_arg;
	registroUsuario  *result_2;
	int  consultarusuario_1_arg;
	registroUsuario  *result_3;
	registroUsuario  autenticar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_usuario_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = almacenarusuario_1(&almacenarusuario_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = consultarusuario_1(&consultarusuario_1_arg, clnt);
	if (result_2 == (registroUsuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = autenticar_1(&autenticar_1_arg, clnt);
	if (result_3 == (registroUsuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
