/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionUsuarios.h"

bool_t
xdr_registroUsuario (XDR *xdrs, registroUsuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->identificacion))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->departamento, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->role, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->login, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
