/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONANTEPROYECTOS_H_RPCGEN
#define _GESTIONANTEPROYECTOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 40
#define MAXCONTENIDO 200

typedef struct nodo_anteproyecto *listaAnteproyectos;

struct datos_anteproyecto {
	int codigoAnteproyecto;
	char nombrePrograma[MAXNOM];
	char titulo[MAXNOM];
	char objetivos[MAXCONTENIDO];
	char estudiante01Nom[MAXNOM];
	int estudiante01Cod;
	char estudiante02Nom[MAXNOM];
	int estudiante02Cod;
	char director[MAXNOM];
	char codirector[MAXNOM];
	evaluacion infoEval[2];
	coordinacion infoCoordi;
	jefeDepto infoJefeDepto;
};
typedef struct datos_anteproyecto datos_anteproyecto;

struct evaluacion {
	char nombre[MAXNOM];
	char fecha[MAXNOM];
	bool_t concepto;
	char observaciones[MAXCONTENIDO];
};
typedef struct evaluacion evaluacion;

struct coordinacion {
	bool_t estructura;
	bool_t concepto;
	char observaciones[MAXCONTENIDO];
};
typedef struct coordinacion coordinacion;

struct jefeDepto {
	bool_t estructura;
	bool_t concepto;
	char observaciones[MAXCONTENIDO];
};
typedef struct jefeDepto jefeDepto;

struct datos_usuario {
	int identificacion;
	char departamento[MAXNOM];
	char role[MAXNOM];
	char nombre[MAXNOM];
	char login[MAXNOM];
	char password[MAXNOM];
};
typedef struct datos_usuario datos_usuario;

#define gestion_anteproyecto 0x20000012
#define gestion_anteproyectos_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarAnteproyecto 1
extern  bool_t * registraranteproyecto_1(datos_anteproyecto *, CLIENT *);
extern  bool_t * registraranteproyecto_1_svc(datos_anteproyecto *, struct svc_req *);
#define registrarResolucion 2
extern  bool_t * registrarresolucion_1(datos_resolucion *, CLIENT *);
extern  bool_t * registrarresolucion_1_svc(datos_resolucion *, struct svc_req *);
#define consultarAnteproyectos 3
extern  listaAnteproyectos * consultaranteproyectos_1(char **, CLIENT *);
extern  listaAnteproyectos * consultaranteproyectos_1_svc(char **, struct svc_req *);
#define consultarAnteproyecto 4
extern  datos_anteproyecto * consultaranteproyecto_1(int *, CLIENT *);
extern  datos_anteproyecto * consultaranteproyecto_1_svc(int *, struct svc_req *);
#define registrarUsuario 5
extern  bool_t * registrarusuario_1(datos_usuario *, CLIENT *);
extern  bool_t * registrarusuario_1_svc(datos_usuario *, struct svc_req *);
#define iniciarSesion 6
extern  datos_usuario * iniciarsesion_1(datos_usuario *, CLIENT *);
extern  datos_usuario * iniciarsesion_1_svc(datos_usuario *, struct svc_req *);
extern int gestion_anteproyecto_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarAnteproyecto 1
extern  bool_t * registraranteproyecto_1();
extern  bool_t * registraranteproyecto_1_svc();
#define registrarResolucion 2
extern  bool_t * registrarresolucion_1();
extern  bool_t * registrarresolucion_1_svc();
#define consultarAnteproyectos 3
extern  listaAnteproyectos * consultaranteproyectos_1();
extern  listaAnteproyectos * consultaranteproyectos_1_svc();
#define consultarAnteproyecto 4
extern  datos_anteproyecto * consultaranteproyecto_1();
extern  datos_anteproyecto * consultaranteproyecto_1_svc();
#define registrarUsuario 5
extern  bool_t * registrarusuario_1();
extern  bool_t * registrarusuario_1_svc();
#define iniciarSesion 6
extern  datos_usuario * iniciarsesion_1();
extern  datos_usuario * iniciarsesion_1_svc();
extern int gestion_anteproyecto_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_listaAnteproyectos (XDR *, listaAnteproyectos*);
extern  bool_t xdr_datos_anteproyecto (XDR *, datos_anteproyecto*);
extern  bool_t xdr_evaluacion (XDR *, evaluacion*);
extern  bool_t xdr_coordinacion (XDR *, coordinacion*);
extern  bool_t xdr_jefeDepto (XDR *, jefeDepto*);
extern  bool_t xdr_datos_usuario (XDR *, datos_usuario*);

#else /* K&R C */
extern bool_t xdr_listaAnteproyectos ();
extern bool_t xdr_datos_anteproyecto ();
extern bool_t xdr_evaluacion ();
extern bool_t xdr_coordinacion ();
extern bool_t xdr_jefeDepto ();
extern bool_t xdr_datos_usuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONANTEPROYECTOS_H_RPCGEN */
