/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONUSUARIOS_H_RPCGEN
#define _GESTIONUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 40

struct registroUsuario {
	int identificacion;
	char departamento[MAXNOM];
	char role[MAXNOM];
	char nombre[MAXNOM];
	char login[MAXNOM];
	char password[MAXNOM];
};
typedef struct registroUsuario registroUsuario;

#define gestion_usuarios 0x20000013
#define gestion_usuario_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define almacenarUsuario 1
extern  bool_t * almacenarusuario_1(registroUsuario *, CLIENT *);
extern  bool_t * almacenarusuario_1_svc(registroUsuario *, struct svc_req *);
#define consultarUsuario 2
extern  registroUsuario * consultarusuario_1(int *, CLIENT *);
extern  registroUsuario * consultarusuario_1_svc(int *, struct svc_req *);
#define autenticar 3
extern  registroUsuario * autenticar_1(registroUsuario *, CLIENT *);
extern  registroUsuario * autenticar_1_svc(registroUsuario *, struct svc_req *);
extern int gestion_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define almacenarUsuario 1
extern  bool_t * almacenarusuario_1();
extern  bool_t * almacenarusuario_1_svc();
#define consultarUsuario 2
extern  registroUsuario * consultarusuario_1();
extern  registroUsuario * consultarusuario_1_svc();
#define autenticar 3
extern  registroUsuario * autenticar_1();
extern  registroUsuario * autenticar_1_svc();
extern int gestion_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registroUsuario (XDR *, registroUsuario*);

#else /* K&R C */
extern bool_t xdr_registroUsuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONUSUARIOS_H_RPCGEN */
