/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SEGUIMIENTOANTEPROYECTOS_H_RPCGEN
#define _SEGUIMIENTOANTEPROYECTOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOMBRE 40
#define MAXCONTE 200

struct registroEvaluacion {
	char nombre[MAXNOMBRE];
	char fecha[MAXNOMBRE];
	bool_t concepto;
	char observaciones[MAXCONTE];
};
typedef struct registroEvaluacion registroEvaluacion;

struct registroCoordinacion {
	bool_t estructura;
	bool_t concepto;
	char observaciones[MAXCONTE];
};
typedef struct registroCoordinacion registroCoordinacion;

struct jefeDepartamento {
	bool_t estructura;
	bool_t concepto;
	char observaciones[MAXCONTE];
};
typedef struct jefeDepartamento jefeDepartamento;

struct registroAnteproyecto {
	int codigoAnteproyecto;
	char nombrePrograma[MAXNOMBRE];
	char titulo[MAXNOMBRE];
	char objetivos[MAXCONTE];
	char estudiante01Nom[MAXNOMBRE];
	int estudiante01Cod;
	char estudiante02Nom[MAXNOMBRE];
	int estudiante02Cod;
	char director[MAXNOMBRE];
	char codirector[MAXNOMBRE];
	registroEvaluacion infoEval[2];
	registroCoordinacion infoCoordi;
	jefeDepartamento infoJefeDepto;
};
typedef struct registroAnteproyecto registroAnteproyecto;

struct registroResolucion {
	int codigoAnteproyecto;
	char fechaResolucion[MAXNOMBRE];
	int numResolucion;
};
typedef struct registroResolucion registroResolucion;

#define gestion_seguimiento 0x20000012
#define gestion_anteproyecto_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define guardarAnteproyecto 1
extern  bool_t * guardaranteproyecto_1(registroAnteproyecto *, CLIENT *);
extern  bool_t * guardaranteproyecto_1_svc(registroAnteproyecto *, struct svc_req *);
#define consultarAnteproyecto 2
extern  registroAnteproyecto * consultaranteproyecto_1(int *, CLIENT *);
extern  registroAnteproyecto * consultaranteproyecto_1_svc(int *, struct svc_req *);
extern int gestion_seguimiento_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define guardarAnteproyecto 1
extern  bool_t * guardaranteproyecto_1();
extern  bool_t * guardaranteproyecto_1_svc();
#define consultarAnteproyecto 2
extern  registroAnteproyecto * consultaranteproyecto_1();
extern  registroAnteproyecto * consultaranteproyecto_1_svc();
extern int gestion_seguimiento_1_freeresult ();
#endif /* K&R C */
#define gestion_resolucion_version 2

#if defined(__STDC__) || defined(__cplusplus)
#define guardarResolucion 1
extern  bool_t * guardarresolucion_2(registroResolucion *, CLIENT *);
extern  bool_t * guardarresolucion_2_svc(registroResolucion *, struct svc_req *);
#define consultarResolucion 2
extern  registroResolucion * consultarresolucion_2(int *, CLIENT *);
extern  registroResolucion * consultarresolucion_2_svc(int *, struct svc_req *);
extern int gestion_seguimiento_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define guardarResolucion 1
extern  bool_t * guardarresolucion_2();
extern  bool_t * guardarresolucion_2_svc();
#define consultarResolucion 2
extern  registroResolucion * consultarresolucion_2();
extern  registroResolucion * consultarresolucion_2_svc();
extern int gestion_seguimiento_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registroEvaluacion (XDR *, registroEvaluacion*);
extern  bool_t xdr_registroCoordinacion (XDR *, registroCoordinacion*);
extern  bool_t xdr_jefeDepartamento (XDR *, jefeDepartamento*);
extern  bool_t xdr_registroAnteproyecto (XDR *, registroAnteproyecto*);
extern  bool_t xdr_registroResolucion (XDR *, registroResolucion*);

#else /* K&R C */
extern bool_t xdr_registroEvaluacion ();
extern bool_t xdr_registroCoordinacion ();
extern bool_t xdr_jefeDepartamento ();
extern bool_t xdr_registroAnteproyecto ();
extern bool_t xdr_registroResolucion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SEGUIMIENTOANTEPROYECTOS_H_RPCGEN */
