/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SEGUIMIENTOANTEPROYECTOS_H_RPCGEN
#define _SEGUIMIENTOANTEPROYECTOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 40

typedef struct nodo_anteproyecto *listaAnteproyectos;

typedef struct nodo_resolucion *listaResoluciones;

struct datos_anteproyecto {
	int codigoAnteproyecto;
	char nombrePrograma[MAXNOM];
	char titulo[MAXNOM];
	char objetivos[MAXCONTENIDO];
	char estudiante01Nom[MAXNOM];
	int estudiante01Cod;
	char estudiante02Nom[MAXNOM];
	int estudiante02Cod;
	char director[MAXNOM];
	char codirector[MAXNOM];
	evaluacion infoEval[2];
	coordinacion infoCoordi;
	jefeDepto infoJefeDepto;
};
typedef struct datos_anteproyecto datos_anteproyecto;

struct datos_resolucion {
	int codigoAnteproyecto;
	char fechaResolucion[MAXNOM];
	int numResolucion;
};
typedef struct datos_resolucion datos_resolucion;

#define gestion_usuarios 0x20000013
#define gestion_seguimiento_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarAnteproyectoHistorial 1
extern  bool_t * registraranteproyectohistorial_1(datos_anteproyecto *, CLIENT *);
extern  bool_t * registraranteproyectohistorial_1_svc(datos_anteproyecto *, struct svc_req *);
#define registrarResolucion 2
extern  bool_t * registrarresolucion_1(datos_resolucion *, CLIENT *);
extern  bool_t * registrarresolucion_1_svc(datos_resolucion *, struct svc_req *);
#define consultarAnteproyectos 3
extern  listaAnteproyectos * consultaranteproyectos_1(void *, CLIENT *);
extern  listaAnteproyectos * consultaranteproyectos_1_svc(void *, struct svc_req *);
#define consultarAprovados 4
extern  listaResoluciones * consultaraprovados_1(void *, CLIENT *);
extern  listaResoluciones * consultaraprovados_1_svc(void *, struct svc_req *);
#define consultarAnteproyecto 5
extern  datos_anteproyecto * consultaranteproyecto_1(int *, CLIENT *);
extern  datos_anteproyecto * consultaranteproyecto_1_svc(int *, struct svc_req *);
#define consultarAprovado 6
extern  datos_resolucion * consultaraprovado_1(int *, CLIENT *);
extern  datos_resolucion * consultaraprovado_1_svc(int *, struct svc_req *);
extern int gestion_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarAnteproyectoHistorial 1
extern  bool_t * registraranteproyectohistorial_1();
extern  bool_t * registraranteproyectohistorial_1_svc();
#define registrarResolucion 2
extern  bool_t * registrarresolucion_1();
extern  bool_t * registrarresolucion_1_svc();
#define consultarAnteproyectos 3
extern  listaAnteproyectos * consultaranteproyectos_1();
extern  listaAnteproyectos * consultaranteproyectos_1_svc();
#define consultarAprovados 4
extern  listaResoluciones * consultaraprovados_1();
extern  listaResoluciones * consultaraprovados_1_svc();
#define consultarAnteproyecto 5
extern  datos_anteproyecto * consultaranteproyecto_1();
extern  datos_anteproyecto * consultaranteproyecto_1_svc();
#define consultarAprovado 6
extern  datos_resolucion * consultaraprovado_1();
extern  datos_resolucion * consultaraprovado_1_svc();
extern int gestion_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_listaAnteproyectos (XDR *, listaAnteproyectos*);
extern  bool_t xdr_listaResoluciones (XDR *, listaResoluciones*);
extern  bool_t xdr_datos_anteproyecto (XDR *, datos_anteproyecto*);
extern  bool_t xdr_datos_resolucion (XDR *, datos_resolucion*);

#else /* K&R C */
extern bool_t xdr_listaAnteproyectos ();
extern bool_t xdr_listaResoluciones ();
extern bool_t xdr_datos_anteproyecto ();
extern bool_t xdr_datos_resolucion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SEGUIMIENTOANTEPROYECTOS_H_RPCGEN */
