/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "seguimientoAnteproyectos.h"

bool_t
xdr_registroEvaluacion (XDR *xdrs, registroEvaluacion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->observaciones, MAXCONTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_registroCoordinacion (XDR *xdrs, registroCoordinacion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_bool (xdrs, &objp->estructura))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->observaciones, MAXCONTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_jefeDepartamento (XDR *xdrs, jefeDepartamento *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_bool (xdrs, &objp->estructura))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->observaciones, MAXCONTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_registroAnteproyecto (XDR *xdrs, registroAnteproyecto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoAnteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombrePrograma, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->objetivos, MAXCONTE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante01Nom, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estudiante01Cod))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante02Nom, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estudiante02Cod))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codirector, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->infoEval, 2,
		sizeof (registroEvaluacion), (xdrproc_t) xdr_registroEvaluacion))
		 return FALSE;
	 if (!xdr_registroCoordinacion (xdrs, &objp->infoCoordi))
		 return FALSE;
	 if (!xdr_jefeDepartamento (xdrs, &objp->infoJefeDepto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_registroResolucion (XDR *xdrs, registroResolucion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoAnteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fechaResolucion, MAXNOMBRE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numResolucion))
		 return FALSE;
	return TRUE;
}
