/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "seguimientoAnteproyectos.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
registraranteproyectohistorial_1(datos_anteproyecto *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrarAnteproyectoHistorial,
		(xdrproc_t) xdr_datos_anteproyecto, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
registrarresolucion_1(datos_resolucion *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrarResolucion,
		(xdrproc_t) xdr_datos_resolucion, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listaAnteproyectos *
consultaranteproyectos_1(void *argp, CLIENT *clnt)
{
	static listaAnteproyectos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarAnteproyectos,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listaAnteproyectos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listaResoluciones *
consultaraprovados_1(void *argp, CLIENT *clnt)
{
	static listaResoluciones clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarAprovados,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listaResoluciones, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_anteproyecto *
consultaranteproyecto_1(int *argp, CLIENT *clnt)
{
	static datos_anteproyecto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarAnteproyecto,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_anteproyecto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datos_resolucion *
consultaraprovado_1(int *argp, CLIENT *clnt)
{
	static datos_resolucion clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarAprovado,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_datos_resolucion, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
