/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "seguimientoAnteproyectos.h"

bool_t
xdr_listaAnteproyectos (XDR *xdrs, listaAnteproyectos *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_anteproyecto), (xdrproc_t) xdr_nodo_anteproyecto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listaResoluciones (XDR *xdrs, listaResoluciones *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_resolucion), (xdrproc_t) xdr_nodo_resolucion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_anteproyecto (XDR *xdrs, datos_anteproyecto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoAnteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombrePrograma, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->objetivos, MAXCONTENIDO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante01Nom, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estudiante01Cod))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante02Nom, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estudiante02Cod))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codirector, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->infoEval, 2,
		sizeof (evaluacion), (xdrproc_t) xdr_evaluacion))
		 return FALSE;
	 if (!xdr_coordinacion (xdrs, &objp->infoCoordi))
		 return FALSE;
	 if (!xdr_jefeDepto (xdrs, &objp->infoJefeDepto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_resolucion (XDR *xdrs, datos_resolucion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoAnteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fechaResolucion, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numResolucion))
		 return FALSE;
	return TRUE;
}
