/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "seguimientoAnteproyectos.h"


void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_anteproyecto  registraranteproyectohistorial_1_arg;
	bool_t  *result_2;
	datos_resolucion  registrarresolucion_1_arg;
	listaAnteproyectos  *result_3;
	char *consultaranteproyectos_1_arg;
	listaResoluciones  *result_4;
	char *consultaraprovados_1_arg;
	datos_anteproyecto  *result_5;
	int  consultaranteproyecto_1_arg;
	datos_resolucion  *result_6;
	int  consultaraprovado_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_seguimiento_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registraranteproyectohistorial_1(&registraranteproyectohistorial_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = registrarresolucion_1(&registrarresolucion_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consultaranteproyectos_1((void*)&consultaranteproyectos_1_arg, clnt);
	if (result_3 == (listaAnteproyectos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = consultaraprovados_1((void*)&consultaraprovados_1_arg, clnt);
	if (result_4 == (listaResoluciones *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = consultaranteproyecto_1(&consultaranteproyecto_1_arg, clnt);
	if (result_5 == (datos_anteproyecto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = consultaraprovado_1(&consultaraprovado_1_arg, clnt);
	if (result_6 == (datos_resolucion *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
