/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionAnteproyectos.h"


void
gestion_anteproyecto_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_anteproyecto  registraranteproyecto_1_arg;
	bool_t  *result_2;
	datos_resolucion  registrarresolucion_1_arg;
	listaAnteproyectos  *result_3;
	char * consultaranteproyectos_1_arg;
	datos_anteproyecto  *result_4;
	int  consultaranteproyecto_1_arg;
	bool_t  *result_5;
	datos_usuario  registrarusuario_1_arg;
	datos_usuario  *result_6;
	datos_usuario  iniciarsesion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_anteproyecto, gestion_anteproyectos_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registraranteproyecto_1(&registraranteproyecto_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = registrarresolucion_1(&registrarresolucion_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consultaranteproyectos_1(&consultaranteproyectos_1_arg, clnt);
	if (result_3 == (listaAnteproyectos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = consultaranteproyecto_1(&consultaranteproyecto_1_arg, clnt);
	if (result_4 == (datos_anteproyecto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = registrarusuario_1(&registrarusuario_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = iniciarsesion_1(&iniciarsesion_1_arg, clnt);
	if (result_6 == (datos_usuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_anteproyecto_1 (host);
exit (0);
}
