/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionAnteproyectos.h"


void
gestion_anteproyecto_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_anteproyecto  registraranteproyecto_1_arg;
	datos_anteproyecto  *result_2;
	int  obteneranteproyecto_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_anteproyecto, gestion_anteproyectos_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registraranteproyecto_1(&registraranteproyecto_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = obteneranteproyecto_1(&obteneranteproyecto_1_arg, clnt);
	if (result_2 == (datos_anteproyecto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
gestion_anteproyecto_2(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_resolucion  registrarresolucion_2_arg;
	datos_resolucion  *result_2;
	int  obtenerresolucion_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_anteproyecto, gestion_resoluciones_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarresolucion_2(&registrarresolucion_2_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = obtenerresolucion_2(&obtenerresolucion_2_arg, clnt);
	if (result_2 == (datos_resolucion *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
gestion_anteproyecto_3(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_usuario  registrarusuario_3_arg;
	datos_usuario  *result_2;
	int  obtenerusuario_3_arg;
	datos_usuario  *result_3;
	datos_usuario  iniciarsesion_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_anteproyecto, gestion_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarusuario_3(&registrarusuario_3_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = obtenerusuario_3(&obtenerusuario_3_arg, clnt);
	if (result_2 == (datos_usuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = iniciarsesion_3(&iniciarsesion_3_arg, clnt);
	if (result_3 == (datos_usuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_anteproyecto_1 (host);
	gestion_anteproyecto_2 (host);
	gestion_anteproyecto_3 (host);
exit (0);
}
