/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionAnteproyectos.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_anteproyecto_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_anteproyecto registraranteproyecto_1_arg;
		int obteneranteproyecto_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrarAnteproyecto:
		_xdr_argument = (xdrproc_t) xdr_datos_anteproyecto;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registraranteproyecto_1_svc;
		break;

	case obtenerAnteproyecto:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_datos_anteproyecto;
		local = (char *(*)(char *, struct svc_req *)) obteneranteproyecto_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
gestion_anteproyecto_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_resolucion registrarresolucion_2_arg;
		int obtenerresolucion_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrarResolucion:
		_xdr_argument = (xdrproc_t) xdr_datos_resolucion;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarresolucion_2_svc;
		break;

	case obtenerResolucion:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_datos_resolucion;
		local = (char *(*)(char *, struct svc_req *)) obtenerresolucion_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
gestion_anteproyecto_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_usuario registrarusuario_3_arg;
		int obtenerusuario_3_arg;
		datos_usuario iniciarsesion_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrarUsuario:
		_xdr_argument = (xdrproc_t) xdr_datos_usuario;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarusuario_3_svc;
		break;

	case obtenerUsuario:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_datos_usuario;
		local = (char *(*)(char *, struct svc_req *)) obtenerusuario_3_svc;
		break;

	case iniciarSesion:
		_xdr_argument = (xdrproc_t) xdr_datos_usuario;
		_xdr_result = (xdrproc_t) xdr_datos_usuario;
		local = (char *(*)(char *, struct svc_req *)) iniciarsesion_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_anteproyecto, gestion_anteproyectos_version);
	pmap_unset (gestion_anteproyecto, gestion_resoluciones_version);
	pmap_unset (gestion_anteproyecto, gestion_usuarios_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_anteproyectos_version, gestion_anteproyecto_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_anteproyectos_version, udp).");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_resoluciones_version, gestion_anteproyecto_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_resoluciones_version, udp).");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_usuarios_version, gestion_anteproyecto_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_usuarios_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_anteproyectos_version, gestion_anteproyecto_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_anteproyectos_version, tcp).");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_resoluciones_version, gestion_anteproyecto_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_resoluciones_version, tcp).");
		exit(1);
	}
	if (!svc_register(transp, gestion_anteproyecto, gestion_usuarios_version, gestion_anteproyecto_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_anteproyecto, gestion_usuarios_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
