/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "seguimientoAnteproyectos.h"

bool_t *
guardaranteproyecto_1_svc(registroAnteproyecto *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\ninvocado\n");
	/*
	 * insert server code here
	 */

	return &result;
}

registroAnteproyecto *
consultaranteproyecto_1_svc(int *argp, struct svc_req *rqstp)
{
	static registroAnteproyecto  result;
	printf("\ninvocado\n");
	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
guardarresolucion_2_svc(registroResolucion *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\ninvocado\n");
	/*
	 * insert server code here
	 */

	return &result;
}

registroResolucion *
consultarresolucion_2_svc(int *argp, struct svc_req *rqstp)
{
	static registroResolucion  result;
	printf("\ninvocado\n");
	/*
	 * insert server code here
	 */

	return &result;
}
