/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "seguimientoAnteproyectos.h"

bool_t *
registraranteproyectohistorial_1_svc(datos_anteproyecto *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
registrarresolucion_1_svc(datos_resolucion *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listaAnteproyectos *
consultaranteproyectos_1_svc(void *argp, struct svc_req *rqstp)
{
	static listaAnteproyectos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listaResoluciones *
consultaraprovados_1_svc(void *argp, struct svc_req *rqstp)
{
	static listaResoluciones  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_anteproyecto *
consultaranteproyecto_1_svc(int *argp, struct svc_req *rqstp)
{
	static datos_anteproyecto  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_resolucion *
consultaraprovado_1_svc(int *argp, struct svc_req *rqstp)
{
	static datos_resolucion  result;

	/*
	 * insert server code here
	 */

	return &result;
}
